Create AltStore repository
Fladder-App/Fladder pull request #23
Opened 2024-10-16 04:15 UTC by bazzadazza72

I would like to propose a contribution in the form of a custom [AltStore](https://altstore.io/) repository which will make installation easier until the iOS app can be published to the App Store (whenever that ends up happening).

The repository currently does not have any apps listed in it, however, I'd be good to add a release once we get iOS compilation working properly.

I can also create some documentation to teach users how to add the repository to their devices, let me know if you want that done too.

Screenshot of the repository in its current state:
![IMG_0132](https://github.com/user-attachments/assets/ce83855d-c090-4eb0-8cbf-f69e7b3ffe12)

2024-10-16 13:37 UTC, PartyDonut commented
That's a good idea would make it easier for iPhone users to side-load the app.
Could you also mark this PR as a draft so we can keep better track of what should or should not be reviewed entirely? 
Or atleast I'm assuming the json needs more information to properly work?

2024-10-16 13:40 UTC, PartyDonut requested changes

2024-10-16 13:40 UTC, PartyDonut commented on altstore.json
> +  "tintColor": "#F54F32",
The current icon background is #3a2101

2024-10-17 11:18 UTC, bazzadazza72 commented
My apologies for going radio silent over the past couple days.

After a large amount of troubleshooting (and many commits as you can see), I have finally gotten the repository to work (I use AltServer in a VM that isn't powered on right now, so I'll test if the app installs later).

If you want to try before merging, here's the link to the repository: https://raw.githubusercontent.com/bazzadazza72/fladder-develop/refs/heads/develop/altstore.json

2024-10-17 14:24 UTC, PartyDonut approved these changes
Looks good to me thanks for working on this.

Do you know if the altStore app supports a button similar to playstore/appstore? Would be great to display on the landing page on github.

2024-10-17 14:25 UTC, merged

2024-10-17 20:15 UTC, krinkuto11 commented
> Looks good to me thanks for working on this.
> 
> Do you know if the altStore app supports a button similar to playstore/appstore? Would be great to display on the landing page on github.

I just sent a pull request adding this!